### ISSUE TITLE
🐛 [BUG] - Comments don't update when search string changes

### ISSUE THREAD

**Issue by derikk** [Dear-Blueno/dearblueno#40]
### Description

When searching for one string and then changing the query to another string, the comments don't always update. In this case, the comments on the first search result for "test" show up on the first search result for "hello". This requires typing moderately fast so that no empty pages of results come up.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/8694764/200444396-371857e2-d11c-4bff-ac34-3a994150f00f.png">

### Reproduction URL

https://www.dearblueno.net/search

### Reproduction steps

```bash
1. Go to search page
2. Search for "test"
3. Search for "hello"
```

### Browsers

Firefox, Chrome, Safari

**Comment by nicholasvadasz** [comment]
Thanks for bringing this to our attention (and for submitting the first ever Dear Blueno GitHub Issue 🥳)!

I have been generally aware of this problem for a while, and think that it has something to do with the fact that we essentially concatenate two search result lists together for every search, one for the number searches (like 1234 results in Post #1234 showing up), as well as one for actual content searching. Additionally, it may have to do with key mappings, and could probably be entirely resolved with some conditional that checks Post IDs or something similar.

It is true though that if you let the search "reset" (meaning that you clear the search query and the feed actually goes empty), the comments end up being correct. If the underlying cause of this comment shifting is too hard to diagnose, it might be worth it to just trigger this "reset" manually when the search parameter changes.

All in all, the frontend search code is pretty messy (most of it was written under a last minute time crunch), and should probably be entirely rewritten eventually. Just wanted to drop this comment hear incase anyone ever wants to take a look at resolving this.
